name: 'PreRelease'

on: 
    push:
        branches:
          - dev
    workflow_dispatch:

jobs:
    buildAndPush:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
    
          - name: Use Node.js
            uses: actions/setup-node@v2
            with:
              node-version: 14

          - name: Build 
            uses: actions/upload-artifact@v4
            with:
              path: ./

          - name: Download 
            uses: actions/download-artifact@v4 

          - name: Push artifact
            run: curl --fail -u ${{secrets.NEXUS_USERNAME}}:${{secrets.NEXUS_PASSWORD}} --upload-file artifact '${{ secrets.NEXUS_URL }}/${{ github.event_name == 'push' && 'dev' || 'staging' }}/Day-Of-Week'
