name: 'PreRelease'

on: 
    push:
        branches:
          - dev
    workflow_dispatch:

jobs:
    buildAndPush:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
    
          - name: Use Node.js
            uses: actions/setup-node@v2
            with:
              node-version: 14

          - name: Push artifact
            env:
                NEXUS_URL: ${{ secrets.NEXUS_URL }}
                NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
                NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
                ARTIFACT_PATH: ${{ github.ref_name }}
            run:
                |
                curl -u $NEXUS_USERNAME:$NEXUS_PASSWORD --upload-file $ARTIFACT_PATH $NEXUS_URL/repository/${{ github.event_name == 'push' && 'dev' || 'staging' }}/Day-Of-Week