name: 'PreRelease'

on:
    push:
        tags:
          - '[0-9].+[0-9].+[0-9]'

jobs:
    buildAndPush:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
    
          - name: Use Node.js
            uses: actions/setup-node@v2
            with:
              node-version: 14

          - name: Push artifact
            env:
                NEXUS_URL: ${{ secrets.NexusUrl }}
                NEXUS_USERNAME: ${{ secrets.NexusUsername }}
                NEXUS_PASSWORD: ${{ secrets.NexusPassword }}
                ARTIFACT_PATH: ${{ github.ref_name }}
            run:
                |
                curl -u $NEXUS_USERNAME:$NEXUS_PASSWORD --upload-file $ARTIFACT_PATH $NEXUS_URL/repository/Prod/${{ github.ref_name }}